export const AI_GRID_MIN_X = 10;
export const AI_GRID_MIN_Y = 10;
export const AI_GRID_DEFAULT = 50;
export const AI_WINDOW_RESIZE_DEB_TIME = 250;
export const AI_WINDOW_PADDING = 20;
export const AI_KEYBOARD_ARROWS = [37, 38, 39, 40];
export const AI_PATH_MANUAL_INTERVAL = 150;
export const AI_PATH_AUTO_INTERVAL = 1;
export const AI_PATH_OPRATION_MODE = 'MANUAL';
